version: '3'
services:
  app:
    image: diasdra/4640app:latest
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file: variables.env
  web:
    image: diasdra/4640web:latest
    ports:
      - 8080:80
    env_file: variables.env