version: '3'
services:
  app:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file: variables.env
  web:
    build:
      dockerfile: ./html/Dockerfile
    ports:
      - 8080:80
    env_file: variables.env